# Generated by Django 5.1.7 on 2025-05-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
