# Generated by Django 5.1.7 on 2025-05-03 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='pphoto',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='ProfilePhoto'),
            preserve_default=False,
        ),
    ]
