# Generated by Django 5.1.7 on 2025-05-12 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0003_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
