# Generated by Django 5.1.7 on 2025-05-12 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0004_notes_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Recjectd')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='notes',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noteapp.usersignup'),
        ),
    ]
